import { test, expect } from "@playwright/test";
import { AUTH_STATE } from "./support/constants";

test.describe("audit logs — super admin", () => {
  test.use({ storageState: AUTH_STATE.superAdmin });

  test("table loads with rows generated by earlier actions in this run, and filters narrow them", async ({ page }) => {
    await page.goto("/admin/audit-logs");
    const rows = page.locator("table tbody tr");
    await expect(rows.first()).toBeVisible();
    const totalCount = await rows.count();
    expect(totalCount).toBeGreaterThan(0);

    // Search narrows the result set (or shows the explicit no-match state).
    await page.getByPlaceholder("Search by actor, action, entity, or ID...").fill("zzz-no-such-actor-zzz");
    await expect(page.getByText("No logs match your filters.")).toBeVisible();
    await page.getByPlaceholder("Search by actor, action, entity, or ID...").fill("");

    // Action filter select is populated from real data and narrows results.
    const actionSelect = page.locator("select").first();
    const actionOptionsCount = await actionSelect.locator("option").count();
    expect(actionOptionsCount).toBeGreaterThan(1);
    const firstRealAction = await actionSelect.locator("option").nth(1).getAttribute("value");
    await actionSelect.selectOption(firstRealAction!);
    const filteredRows = await page.locator("table tbody tr").count();
    expect(filteredRows).toBeGreaterThan(0);
    await actionSelect.selectOption("all");

    // Entity filter select likewise.
    const entitySelect = page.locator("select").nth(1);
    const entityOptionsCount = await entitySelect.locator("option").count();
    expect(entityOptionsCount).toBeGreaterThan(1);
  });
});

test.describe("audit logs — admin", () => {
  test.use({ storageState: AUTH_STATE.admin });

  test("nav link is visible for ADMIN, matching the backend's own role gate", async ({
    page,
  }) => {
    await page.goto("/admin/audit-logs");
    await expect(page.getByRole("link", { name: "Audit Logs", exact: true })).toBeVisible();
    await expect(page.locator("table tbody tr").first()).toBeVisible();
  });
});

test.describe("audit logs — field executive", () => {
  test.use({ storageState: AUTH_STATE.fieldExecutive });

  test("nav link is absent and direct navigation shows a permission-denied message", async ({ page }) => {
    await page.goto("/admin/audit-logs");
    await expect(page.getByRole("link", { name: "Audit Logs", exact: true })).toHaveCount(0);
    await expect(page.getByText("You don't have permission to view audit logs.")).toBeVisible();
  });
});
